WITH anch (AOB_ID,AOB_HIERARCHY_LEVEL, AOB_TYPE_ID, AOB_PARENT_ID,AOB_FORMAL_NAME,AOB_REVERSE_PATH,AOB_IFNSFL) AS
(SELECT AOB_ID, AOB_HIERARCHY_LEVEL, AOB_TYPE_ID, AOB_PARENT_ID, AOB_FORMAL_NAME, AOB_REVERSE_PATH, AOB_IFNSFL 
    FROM DICT_ADDRESS_OBJECT dao
    WHERE dao.AOB_ID = 5474551
UNION ALL
SELECT dao2.AOB_ID,dao2.AOB_HIERARCHY_LEVEL, dao2.AOB_TYPE_ID, dao2.AOB_PARENT_ID, dao2.AOB_FORMAL_NAME, dao2.AOB_REVERSE_PATH, dao2.AOB_IFNSFL 
    FROM DICT_ADDRESS_OBJECT dao2
        INNER JOIN anch ON dao2.AOB_ID=anch.AOB_PARENT_ID)

SELECT anch.AOB_ID, anch.AOB_HIERARCHY_LEVEL, DAOT.AOT_NAME , AOB_PARENT_ID, AOB_FORMAL_NAME, AOB_REVERSE_PATH, AOB_IFNSFL, AOB_REVERSE_PATH
    FROM anch 
        JOIN DICT_ADDRESS_OBJECT_TYPE daot ON anch.AOB_TYPE_ID=daot.AOT_ID 
    ORDER BY AOB_HIERARCHY_LEVEL;